name: Ruff Lint

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - nonebot_plugin_game_torrent/**
      - pyproject.toml
      - uv.lock
      - .ruff.toml
      - tests/**
      - .github/workflows/ruff-check.yml

jobs:
  ruff:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.18"
      - run: uv sync --locked --only-group dev
      - run: uv run --locked ruff check .
      - run: uv run --locked ruff format --check .
